"""init

Revision ID: 65d4e24dc330
Revises: 
Create Date: 2026-07-09 14:42:47.458225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d4e24dc330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('manager_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('bay', sa.String(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='seatstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor', 'zone', 'seat_number', name='uq_seat_location')
    )
    op.create_index('ix_seats_floor_zone', 'seats', ['floor', 'zone'], unique=False)
    op.create_index('ix_seats_status', 'seats', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING_ALLOCATION', name='employeestatus'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index('ix_employees_project_id', 'employees', ['project_id'], unique=False)
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False)
    op.create_table('seat_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('allocation_status', sa.Enum('ACTIVE', 'RELEASED', name='allocationstatus'), nullable=False),
    sa.Column('allocation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seat_allocations_emp_status', 'seat_allocations', ['employee_id', 'allocation_status'], unique=False)
    op.create_index('ix_seat_allocations_seat_status', 'seat_allocations', ['seat_id', 'allocation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seat_allocations_seat_status', table_name='seat_allocations')
    op.drop_index('ix_seat_allocations_emp_status', table_name='seat_allocations')
    op.drop_table('seat_allocations')
    op.drop_index('ix_employees_status', table_name='employees')
    op.drop_index('ix_employees_project_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_seats_status', table_name='seats')
    op.drop_index('ix_seats_floor_zone', table_name='seats')
    op.drop_table('seats')
    op.drop_table('projects')
    # ### end Alembic commands ###
